import { Geist, Geist_Mono, Cormorant_Infant, Urbanist, Bona_Nova_SC, Bona_Nova} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const BonaNovaSCFont = Bona_Nova_SC({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bona_nova_sc",
});

const BonaNovaFont = Bona_Nova({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bona_nova",
});

const CormorantInfantFont = Cormorant_Infant({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cormorant_infant",
});

const UrbanistFont = Urbanist({
  subsets: ["latin"],
  weight: ["200", "400"],
  variable: "--font-urbanist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import { AuthProvider } from "./context/AuthContext";


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${BonaNovaFont.variable}  ${BonaNovaSCFont.variable}  ${UrbanistFont.variable} ${CormorantInfantFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
